/**
 * Shared plumbing for the integration suite: a MinIO container, the S3 helpers
 * the assertions are written against, and a Config builder.
 *
 * Each test file owns its own container so a file can be run in isolation and
 * so one file's bucket state cannot leak into another's assertions.
 */

import {
  CreateBucketCommand,
  DeleteObjectCommand,
  GetObjectCommand,
  HeadObjectCommand,
  ListObjectsV2Command,
  PutObjectCommand,
  S3Client,
} from "@aws-sdk/client-s3";
import { readFile } from "node:fs/promises";
import { GenericContainer, Wait, type StartedTestContainer } from "testcontainers";

import type { Config, LadderRung, Logger } from "@s3-hls-transcoder/lib";

// Pinned: this image backs a required CI job, so tracking :latest would let an
// upstream release break CI on an unrelated commit.
const MINIO_IMAGE = "minio/minio:RELEASE.2025-04-22T22-12-26Z";
const MINIO_PORT = 9000;
export const MINIO_ACCESS_KEY = "minioadmin";
export const MINIO_SECRET_KEY = "minioadmin";

export const SOURCE_BUCKET = "source";
export const DEST_BUCKET = "dest";

/** A running MinIO with the source and destination buckets already created. */
export interface Harness {
  endpoint: string;
  s3: S3Client;
  stop(): Promise<void>;
}

export async function startMinio(
  buckets: string[] = [SOURCE_BUCKET, DEST_BUCKET],
): Promise<Harness> {
  const container: StartedTestContainer = await new GenericContainer(MINIO_IMAGE)
    .withExposedPorts(MINIO_PORT)
    .withCommand(["server", "/data"])
    .withEnvironment({
      MINIO_ROOT_USER: MINIO_ACCESS_KEY,
      MINIO_ROOT_PASSWORD: MINIO_SECRET_KEY,
    })
    .withWaitStrategy(Wait.forHttp("/minio/health/live", MINIO_PORT))
    .start();

  // getHost(), not a hardcoded loopback: the Docker daemon may not be local
  // (DOCKER_HOST, a VM, or a remote runner).
  const endpoint = `http://${container.getHost()}:${container.getMappedPort(MINIO_PORT)}`;
  const s3 = new S3Client({
    endpoint,
    region: "us-east-1",
    credentials: { accessKeyId: MINIO_ACCESS_KEY, secretAccessKey: MINIO_SECRET_KEY },
    forcePathStyle: true,
  });

  for (const bucket of buckets) {
    await s3.send(new CreateBucketCommand({ Bucket: bucket }));
  }

  return {
    endpoint,
    s3,
    async stop() {
      s3.destroy();
      await container.stop();
    },
  };
}

/** Path of a fixture generated by globalSetup, by its `FIXTURE_*` env var. */
export function fixturePath(name: "SOURCE" | "REMUXED" | "SMALL"): string {
  const value = process.env[`FIXTURE_${name}`];
  if (!value) {
    throw new Error(
      `FIXTURE_${name} is not set — globalSetup did not run. Set INTEGRATION=1 and run via \`vitest run\`.`,
    );
  }
  return value;
}

export async function uploadFixture(
  s3: S3Client,
  bucket: string,
  key: string,
  name: "SOURCE" | "REMUXED" | "SMALL",
): Promise<void> {
  await s3.send(
    new PutObjectCommand({
      Bucket: bucket,
      Key: key,
      Body: await readFile(fixturePath(name)),
      ContentType: "video/mp4",
    }),
  );
}

export async function deleteObject(s3: S3Client, bucket: string, key: string): Promise<void> {
  await s3.send(new DeleteObjectCommand({ Bucket: bucket, Key: key }));
}

export async function objectExists(s3: S3Client, bucket: string, key: string): Promise<boolean> {
  try {
    await s3.send(new HeadObjectCommand({ Bucket: bucket, Key: key }));
    return true;
  } catch {
    return false;
  }
}

export async function listObjects(
  s3: S3Client,
  bucket: string,
  prefix?: string,
): Promise<string[]> {
  const keys: string[] = [];
  let continuationToken: string | undefined;
  do {
    const res = await s3.send(
      new ListObjectsV2Command({
        Bucket: bucket,
        Prefix: prefix,
        ContinuationToken: continuationToken,
      }),
    );
    for (const obj of res.Contents ?? []) {
      if (obj.Key) keys.push(obj.Key);
    }
    continuationToken = res.NextContinuationToken;
  } while (continuationToken);
  return keys.sort();
}

export async function getText(s3: S3Client, bucket: string, key: string): Promise<string> {
  const res = await s3.send(new GetObjectCommand({ Bucket: bucket, Key: key }));
  if (!res.Body) throw new Error(`Empty body for ${key}`);
  return res.Body.transformToString();
}

export async function getJson<T>(s3: S3Client, bucket: string, key: string): Promise<T> {
  return JSON.parse(await getText(s3, bucket, key)) as T;
}

/** Content IDs that have transcoded output, derived from the by-id/ listing. */
export async function contentIdsWithOutput(s3: S3Client, bucket: string): Promise<string[]> {
  const keys = await listObjects(s3, bucket, "by-id/");
  const ids = keys
    .filter((k) => k.endsWith("/master.m3u8"))
    .map((k) => k.slice("by-id/".length, -"/master.m3u8".length));
  return [...new Set(ids)].sort();
}

/**
 * A two-rung ladder. A 640×360 source keeps both rungs; a 320×240 source keeps
 * neither by the "no upscaling" rule and falls back to the smallest, which is
 * what makes ladder filtering observable in the output tree.
 */
export const TEST_LADDER: LadderRung[] = [
  { name: "240p", width: 426, height: 240, videoBitrateKbps: 300, audioBitrateKbps: 64 },
  { name: "360p", width: 640, height: 360, videoBitrateKbps: 600, audioBitrateKbps: 64 },
];

export function makeConfig(endpoint: string, overrides: Partial<Config> = {}): Config {
  const bucketCfg = {
    endpoint,
    accessKeyId: MINIO_ACCESS_KEY,
    secretAccessKey: MINIO_SECRET_KEY,
    region: "us-east-1",
  };
  return {
    pairs: [
      {
        source: { ...bucketCfg, bucket: SOURCE_BUCKET },
        dest: { ...bucketCfg, bucket: DEST_BUCKET },
      },
    ],
    ladder: TEST_LADDER,
    maxRuntimeSeconds: 240,
    lockTtlMultiplier: 1.5,
    budgetMultiplier: 0.9,
    perceptualThreshold: 0.95,
    perceptualDryRun: false,
    cleanupDeletedSources: false,
    cleanupDryRun: false,
    maxConcurrency: 1,
    maxSourceSizeBytes: 1024 * 1024 * 1024,
    maxVideoDurationSeconds: 60,
    logLevel: "info",
    platform: "local",
    ...overrides,
  };
}

export interface LogEntry {
  level: "debug" | "info" | "warn" | "error";
  msg: string;
  fields: Record<string, unknown>;
}

/**
 * A Logger that records everything, so tests can assert on decisions the
 * pipeline only reports through logs (an advisory perceptual match, say), and
 * echoes warnings and errors so a CI failure is diagnosable from the job output.
 */
export function collectingLogger(): { logger: Logger; entries: LogEntry[] } {
  const entries: LogEntry[] = [];
  const record = (level: LogEntry["level"]) => (msg: string, fields?: Record<string, unknown>) => {
    entries.push({ level, msg, fields: fields ?? {} });
    if (level === "warn" || level === "error") console.error("[lib]", level, msg, fields ?? "");
  };
  return {
    entries,
    logger: {
      debug: record("debug"),
      info: record("info"),
      warn: record("warn"),
      error: record("error"),
    },
  };
}
